fix: Update cli command
netlify/feature-tour pull request #28
Opened 2023-08-13 19:47 UTC by bensonarafat

bug in git cli commend

2023-08-14 14:42 UTC, rstavchansky requested changes
Thanks for this PR. Once you revert your update to the `deploy-previews.astro` file, I can accept the PR's update to the README file instructions.

2023-08-14 14:42 UTC, rstavchansky commented on src/pages/deploy-previews.astro
> +    <h2>This is a Deploy Preview</h2>
Can you revert the change to this `deploy-previews.astro` file? We appreciate the fix to the repo name in the README, and we can merge that in once you remove this edit.

2023-08-15 03:13 UTC, bensonarafat commented
Okay now.

2023-08-15 11:48 UTC, rstavchansky approved these changes
Please go ahead and merge this pull request. Thank you for your contribution!

2024-05-24 15:01 UTC, closed without merging